in progress
CyrilPerrinjaquet/MusicBand pull request #2
Opened 2022-09-26 15:13 UTC by CyrilPerrinjaquet

2022-09-27 06:54 UTC, dianedelallee commented on MainMusicBand.java
>                          "dolly parton",
Pas sure que Dolly Parton soit une chanteuse ca serait bien de trouver une autre personne

ex: Fred Aster 😄

2022-09-27 14:17 UTC, mpintoQoQa requested changes

2022-09-27 14:17 UTC, mpintoQoQa commented on MemberBand.java
> +
```suggestion

```

2022-09-27 14:17 UTC, mpintoQoQa commented on MemberBand.java
> +    enum Styles { // peut-être faire des sous styles(ex. funk rock, punk rock etc)
Prend l'habitude de mettre des commentaires en anglais

2022-09-27 14:17 UTC, mpintoQoQa commented on README.md
> +* renommer la class MembersBand en MemberBand // C'est fait
Peut être mettre un petit emoji ✅

2022-09-29 14:54 UTC, CyrilPerrinjaquet commented on MemberBand.java
> +    enum Styles { // peut-être faire des sous styles(ex. funk rock, punk rock etc)
ça marche c'est vrai que je les mets en français pour ma propre compréhension :)

2022-10-03 11:35 UTC, Kevinrob reviewed
Le dossier `out/` ne devrait pas être dans GIT.
Tu peux l'ajouter à ton `.gitignore`.

2022-10-03 11:35 UTC, Kevinrob commented on MemberBand.java
> +        private static final Random NOTE = new Random();
Le nom d'une variable devrait toujours représenter au mieux ce qu'elle contient.
Ici, la variable référence une instance de [`Random`](https://docs.oracle.com/javase/8/docs/api/java/util/Random.html).
Donc, je pense que `NOTE` ne soit pas le meilleur nom.

Peut-être quelque chose comme `random` simplement? Ou `randomGenrator`. Si tu trouve mieux que moi n'hésite pas!

```suggestion
        private static final Random random = new Random();
```

2022-10-03 11:35 UTC, Kevinrob commented on Musician.java
> +    }
Ici, on a un bon candidat pour parler du mot clé `abstract` (qu'on avait rapidement vu une fois).
Si on a le temps, on peut en parler demain lors du point hebdo.

2022-10-07 13:36 UTC, merged